# Utiliser une image de base
FROM python:3.11

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers nécessaires dans le conteneur
COPY script.py /app/script.py
COPY requirements.txt /app/requirements.txt

# Installer les dépendances Python
RUN pip install -r requirements.txt

# Commande par défaut à exécuter lorsque le conteneur démarre
CMD ["python", "script.py"]
